FROM node:24-bookworm

RUN apt-get update && apt-get install -y \
    ripgrep \
    fzf \
    git \
    wget \
    gcc \
    g++ \
    make \
    python3 \
    python3-pip \
    neovim \
    curl \
    jq

WORKDIR /workspace
